language: node.js

services:
  - docker

before_install:
#  - REMOTE_NAME	:= 288007071024.dkr.ecr.ap-southeast-1.amazonaws.com/cutomer-reg-api
#  - TAG 		:= $$(git log -1 --pretty=%h)
#  - LOCAL_IMG 	:= ${NAME}:${TAG}
#  - REMOTE_IMG	:= ${REMOTE_NAME}:${TAG}
  - docker build -t pigball/customer-reg-api -f Dockerfile .
  - docker run -d -p 3000:3000 pigball/customer-reg-api
#  - docker tag ${LOCAL_IMG} ${REMOTE_IMG}

