language: node.js

services:
  - docker

before_install:
  - docker build -t pigball/customer-reg-api -f Dockerfile .
  - docker run -d -p 3000:3000 pigball/customer-reg-api

script:
  - bundle exec rake test

