language: node_js

services:
  - docker

node_js:
  - "12"

cache:
  directories:
    - "node_modules"

before_install:
  - docker build -t pigball/customer-reg-api -f Dockerfile .
  - docker run -d -p 3000:3000 pigball/customer-reg-api
